FROM python:3.10-slim

WORKDIR /service1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install opentelemetry-sdk opentelemetry-exporter-jaeger thrift aio_pika
RUN pip install opentelemetry-instrumentation opentelemetry-api

COPY . .

CMD ["python", "main.py"]
